# Site settings
title: Hyperthetical Ventures
tagline: Building the future, today.
description: > # this means to ignore newlines until "baseurl:"
  Hyperthetical Ventures works across disciplines to build the future, today.
  We pursue special projects and investments across a range of domains, with all
  sharing a common focus: leaving the planet in better shape than we found it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hyperthetical.co" # the base hostname & protocol for your site

# Plugins
gems: ["jekyll-paginate"]

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"